# M-Pesa Daraja credentials for sandbox testing
CONSUMER_KEY = "k0GpF5smVBUyKoDQHTjefIRgUSgNDlgGs6jSvTWkUqxDqFk2"
CONSUMER_SECRET = "vhAGXR9CURPfIp2eUM8JFGqkZ5AlebeA81RPohBUEogCmiMw17pzfdE2LLxbBAMW"
BUSINESS_SHORTCODE = "174379"  # or your sandbox shortcode
PASSKEY = "bfb279f9aa9bdbcf15xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"  # Replace with your full passkey
CALLBACK_URL = "https://mpesa-sub.streamlit.app/callback"

# Optional database/test keys
[database]
DB_USERNAME = "myuser"
DB_TOKEN = "abcdef"

[email]
EMAIL_HOST = "smtp.gmail.com"
EMAIL_PORT = 587
EMAIL_USERNAME = "your_email@gmail.com"
EMAIL_PASSWORD = "your_app_password"
EMAIL_TO = "recipient@example.com"
