CONSUMER_KEY = "k0GpF5smVBUyKoDQHTjefIRgUSgNDlgGs6jSvTWkUqxDqFk2"        # From sandbox app
CONSUMER_SECRET = "vhAGXR9CURPfIp2eUM8JFGqkZ5AlebeA81RPohBUEogCmiMw17pzfdE2LLxbBAMW"  # From sandbox app
BUSINESS_SHORTCODE = "6992220"  # Default sandbox paybill
PASSKEY = "bfb279f9aa9bdbcf158e97dd71a467cd2c2c19f57622c07c3b25d8c5c4f9bf2b"  # Default sandbox passkey
CALLBACK_URL = "https://mpesa-sub.streamlit.app/"
