CONSUMER_KEY = "your_production_consumer_key"
CONSUMER_SECRET = "your_production_consumer_secret"
BUSINESS_SHORTCODE = "123456"
PASSKEY = "your_daraja_passkey"
CALLBACK_URL = "https://your-callback-server.com/mpesa-callback"